### ISSUE TITLE
Plugin don't work after install, empty docker, showing this error...

### ISSUE THREAD

**Issue by valden80** [internationalTD/defuser#6]
Manjaro Linux, Krita 5.1.1

After install docker is empty. If try to "SD check requirements and fix" option, it show this error:

AttributeError
Python 3.10.7: /usr/bin/python3
Sun Oct 30 11:45:33 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/usersd/.local/share/krita/pykrita/Defuser/__init__.py in f()
   31 
   32             docker = self.getDocker()
   33             mode = docker.widget().findChildren(QTabWidget)[0].tabText( docker.widget().findChildren(QTabWidget)[0].currentIndex())
   34             loop_max = 32
   35             while not docker.checkReady(mode) and loop_max >0:
mode undefined
docker = <Defuser.MyDocker.MyDocker object>
docker.widget = <built-in method widget of MyDocker object>
).findChildren undefined
global QTabWidget = <class 'PyQt5.QtWidgets.QTabWidget'>
].tabText = <built-in function tabText>
].currentIndex = <built-in function currentIndex>
AttributeError: 'NoneType' object has no attribute 'findChildren'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'findChildren'",)
    name = 'findChildren'
    obj = None
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/usersd/.local/share/krita/pykrita/Defuser/__init__.py", line 33, in f
    mode = docker.widget().findChildren(QTabWidget)[0].tabText( docker.widget().findChildren(QTabWidget)[0].currentIndex())
AttributeError: 'NoneType' object has no attribute 'findChildren'

**Comment by internationalTD** [comment]
The docker stays empty when Defuser can't connect to the WebUI. 
Is it possible that either the UI is not running on the default localhost:7860, or it didn't **fully launch** (i.e. was accessible in a browser as well) before you opened Krita?

I will improve this behavior in a future release.

**Comment by valden80** [comment]
Yes, it's fully launched, I opened link http://127.0.0.1:7860 in browser and generate test image. Then I start Krita and have empty docker and error.

Also I just updated SD to last version by git pull, and added --api option to the webui-user.sh - nothing changes.

**Comment by internationalTD** [comment]
Thank you very much for your time and help with fixing this issue. 
You shouldn't need the --api argument at all, actually.

I had a bad url string in a GET request somewhere, which meant defuser would only work on a machine with an edited hosts file.

I pushed a new build that hopefully fixes it. Please update and see if defuser starts normally.
If it does not, let me know and i will reopen this.
